config/routes.rb
HustleRose::Application.routes.draw do
  resources :contact_posts

  resources :home_posts

  resources :lyrics

  resources :posts

  resources :videos

  resources :musics

  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/contact"
  
  root  'static_pages#home'
  match '/admin',  to: 'static_pages#admin',            via: 'get'
  match '/contact',  to: 'static_pages#contact',            via: 'get'

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_filter :authenticate, :except => [:home, :contact]
  
  def home
      @home_posts = HomePost.all
  end

  def admin
      @posts = Post.all
      @videos = Video.all
      @musics = Music.all
      @lyrics = Lyric.all
      @home_posts = HomePost.all
      @contact_posts = ContactPost.all 
  end
  
  def contact
      @contact_posts = ContactPost.all 
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/admin.html.erb
<h3>Listing Home Posts</h3>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @home_posts.each do |home_post| %>
      <tr>
        <td><%= home_post.title %></td>
        <td><%= home_post.description %></td>
        <td><%= link_to 'Show', home_post %></td>
        <td><%= link_to 'Edit', edit_home_post_path(home_post) %></td>
        <td><%= link_to 'Destroy', home_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home post', new_home_post_path %>

<h3>Listing Contact Posts</h3>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_posts.each do |contact_post| %>
      <tr>
        <td><%= contact_post.title %></td>
        <td><%= contact_post.description %></td>
        <td><%= link_to 'Show', contact_post %></td>
        <td><%= link_to 'Edit', edit_contact_post_path(contact_post) %></td>
        <td><%= link_to 'Destroy', contact_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact post', new_contact_post_path %>

<h3>Listing Lyrics Posts</h3>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @lyrics.each do |lyric| %>
      <tr>
        <td><%= lyric.title %></td>
        <td><%= lyric.description %></td>
        <td><%= link_to 'Show', lyric %></td>
        <td><%= link_to 'Edit', edit_lyric_path(lyric) %></td>
        <td><%= link_to 'Destroy', lyric, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lyric', new_lyric_path %>

<h3>Listing Video Posts</h3>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @videos.each do |video| %>
      <tr>
        <td><%= video.title %></td>
        <td><%= video.link %></td>
        <td><%= video.description %></td>
        <td><%= link_to 'Show', video %></td>
        <td><%= link_to 'Edit', edit_video_path(video) %></td>
        <td><%= link_to 'Destroy', video, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Video', new_video_path %>

<h3>Listing Music Posts</h3>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.title %></td>
        <td><%= music.link %></td>
        <td><%= music.description %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

<h3>Listing Blog Posts</h3>

<table class = "table table-striped table-hover">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.description %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/static_pages/contact.html.erb
<% @contact_posts.each do |post| %>
    <div class = 'section'>
        <h3 class = 'title'><%= post.title %></h3>
        <p><%= post.description.html_safe %></p>
    </div>
<% end %>

app/views/static_pages/home.html.erb
<% @home_posts.each do |post| %>
    <div class = 'section'>
        <h3 class = 'title'><%= post.title %></h3>
        <p><%= post.description.html_safe %></p>
    </div>
<% end %>