config/routes.rb
HustleRose::Application.routes.draw do
  resources :contact_posts

  resources :home_posts

  resources :lyrics

  resources :posts

  resources :videos

  resources :musics

  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/contact"
  
  root  'static_pages#home'
  match '/admin',  to: 'static_pages#admin',            via: 'get'
  match '/contact',  to: 'static_pages#contact',            via: 'get'

  

end

app/models/home_post.rb
class HomePost < ActiveRecord::Base
end

app/controllers/home_posts_controller.rb
class HomePostsController < ApplicationController
  before_action :set_home_post, only: [:show, :edit, :update, :destroy]

  # GET /home_posts
  # GET /home_posts.json
  def index
    @home_posts = HomePost.all
  end

  # GET /home_posts/1
  # GET /home_posts/1.json
  def show
  end

  # GET /home_posts/new
  def new
    @home_post = HomePost.new
  end

  # GET /home_posts/1/edit
  def edit
  end

  # POST /home_posts
  # POST /home_posts.json
  def create
    @home_post = HomePost.new(home_post_params)

    respond_to do |format|
      if @home_post.save
        format.html { redirect_to @home_post, notice: 'Home post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @home_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @home_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /home_posts/1
  # PATCH/PUT /home_posts/1.json
  def update
    respond_to do |format|
      if @home_post.update(home_post_params)
        format.html { redirect_to @home_post, notice: 'Home post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @home_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /home_posts/1
  # DELETE /home_posts/1.json
  def destroy
    @home_post.destroy
    respond_to do |format|
      format.html { redirect_to home_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_home_post
      @home_post = HomePost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def home_post_params
      params.require(:home_post).permit(:title, :description)
    end
end

app/helpers/home_posts_helper.rb
module HomePostsHelper
end

app/views/home_posts/_form.html.erb
<%= form_for(@home_post) do |f| %>
  <% if @home_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@home_post.errors.count, "error") %> prohibited this home_post from being saved:</h2>

      <ul>
      <% @home_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/home_posts/edit.html.erb
<h1>Editing home_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @home_post %> |
<%= link_to 'Back', home_posts_path %>

app/views/home_posts/index.html.erb
<!--<h1>Listing home_posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @home_posts.each do |home_post| %>
      <tr>
        <td><%= home_post.title %></td>
        <td><%= home_post.description %></td>
        <td><%= link_to 'Show', home_post %></td>
        <td><%= link_to 'Edit', edit_home_post_path(home_post) %></td>
        <td><%= link_to 'Destroy', home_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Home post', new_home_post_path %>-->
<% @home_posts.each do |post| %>
    <div class = 'section'>
        <h3 class = 'title'><%= post.title %></h3>
        <p><%= post.description.html_safe %></p>
    </div>
<% end %>

app/views/home_posts/new.html.erb
<h1>New home_post</h1>

<%= render 'form' %>

<%= link_to 'Back', home_posts_path %>

app/views/home_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @home_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @home_post.description %>
</p>

<%= link_to 'Edit', edit_home_post_path(@home_post) %> |
<%= link_to 'Back', home_posts_path %>