config/routes.rb
HustleRose::Application.routes.draw do
  resources :contact_posts

  resources :home_posts

  resources :lyrics

  resources :posts

  resources :videos

  resources :musics

  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/contact"
  
  root  'static_pages#home'
  match '/admin',  to: 'static_pages#admin',            via: 'get'
  match '/contact',  to: 'static_pages#contact',            via: 'get'

  

end

app/models/contact_post.rb
class ContactPost < ActiveRecord::Base
end

app/controllers/contact_posts_controller.rb
class ContactPostsController < ApplicationController
  before_action :set_contact_post, only: [:show, :edit, :update, :destroy]

  # GET /contact_posts
  # GET /contact_posts.json
  def index
    @contact_posts = ContactPost.all
  end

  # GET /contact_posts/1
  # GET /contact_posts/1.json
  def show
  end

  # GET /contact_posts/new
  def new
    @contact_post = ContactPost.new
  end

  # GET /contact_posts/1/edit
  def edit
  end

  # POST /contact_posts
  # POST /contact_posts.json
  def create
    @contact_post = ContactPost.new(contact_post_params)

    respond_to do |format|
      if @contact_post.save
        format.html { redirect_to @contact_post, notice: 'Contact post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @contact_post }
      else
        format.html { render action: 'new' }
        format.json { render json: @contact_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_posts/1
  # PATCH/PUT /contact_posts/1.json
  def update
    respond_to do |format|
      if @contact_post.update(contact_post_params)
        format.html { redirect_to @contact_post, notice: 'Contact post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @contact_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_posts/1
  # DELETE /contact_posts/1.json
  def destroy
    @contact_post.destroy
    respond_to do |format|
      format.html { redirect_to contact_posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_post
      @contact_post = ContactPost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_post_params
      params.require(:contact_post).permit(:title, :description)
    end
end

app/helpers/contact_posts_helper.rb
module ContactPostsHelper
end

app/views/contact_posts/_form.html.erb
<%= form_for(@contact_post) do |f| %>
  <% if @contact_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_post.errors.count, "error") %> prohibited this contact_post from being saved:</h2>

      <ul>
      <% @contact_post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contact_posts/edit.html.erb
<h1>Editing contact_post</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact_post %> |
<%= link_to 'Back', contact_posts_path %>

app/views/contact_posts/index.html.erb
<!--<h1>Listing contact_posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @contact_posts.each do |contact_post| %>
      <tr>
        <td><%= contact_post.title %></td>
        <td><%= contact_post.description %></td>
        <td><%= link_to 'Show', contact_post %></td>
        <td><%= link_to 'Edit', edit_contact_post_path(contact_post) %></td>
        <td><%= link_to 'Destroy', contact_post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact post', new_contact_post_path %>-->
<% @contact_posts.each do |post| %>
    <div class = 'section'>
        <h3 class = 'title'><%= post.title %></h3>
        <p><%= post.description.html_safe %></p>
    </div>
<% end %>

app/views/contact_posts/new.html.erb
<h1>New contact_post</h1>

<%= render 'form' %>

<%= link_to 'Back', contact_posts_path %>

app/views/contact_posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @contact_post.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @contact_post.description %>
</p>

<%= link_to 'Edit', edit_contact_post_path(@contact_post) %> |
<%= link_to 'Back', contact_posts_path %>