config/routes.rb
HustleRose::Application.routes.draw do
  resources :contact_posts

  resources :home_posts

  resources :lyrics

  resources :posts

  resources :videos

  resources :musics

  get "static_pages/home"
  get "static_pages/admin"
  get "static_pages/contact"
  
  root  'static_pages#home'
  match '/admin',  to: 'static_pages#admin',            via: 'get'
  match '/contact',  to: 'static_pages#contact',            via: 'get'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HustleRose</title>
  
  
  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"></script>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <link href='http://fonts.googleapis.com/css?family=Montserrat+Subrayada' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Rye' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  
  
<%= csrf_meta_tags %>  
</head>
<body><!-- onload ="resize_video()" onresize="resize_video()">-->

    <div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <a id = "navlogo" class="navbar-brand" href=<%= root_path %>>Hustle Rose</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href=<%= root_path %>>Home</a></li>
            <li><a href=<%= musics_path %>>Music</a></li>
            <li><a href=<%= videos_path %>>Videos</a></li>
            <li><a href=<%= lyrics_path %>>Lyrics</a></li>
            <li><a href=<%= posts_path %>>Blog</a></li>
            <li><a href=<%= contact_path %>>Contact</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li><a href=<%= admin_path %>>Admin</a></li>
              <li><a href="http://www.rmaitra.com">Created by Raj Maitra</a></li>
          </ul>
        </div>
      </div>
    </div>
    
    </br>
    </br>
    </br>

    
    <div class = "container">
        <h1 id = "main_title"> Hustle Rose </h1>
        <div class = "jumbotron">
            <%= yield %>
        </div>
    </div>

</body>
</html>